// data/dummyFeed.ts
import { Post } from "@/types/post";

export const dummyFeed: Post[] = [
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/men/32.jpg",
      username: "runner_john",
    },
    imageUri: "https://picsum.photos/600/400?random=1",
    caption: "Morning grind 💪 Finished a solid 10k run today!",
    timestamp: "2h ago",
    postType: "challenge",
    comments: [
      { id: "1", user: "fitgirl", text: "Awesome pace 🔥" },
      { id: "2", user: "coachMike", text: "Keep pushing, John!" },
    ],
    liked: true,
    likesCount: 24,
    status: "In Progress",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/women/45.jpg",
      username: "sarah_fit",
    },
    caption: "Excited to join the Fall Marathon League! 🍂🏃‍♀️",
    timestamp: "5h ago",
    postType: "league",
    liked: false,
    likesCount: 18,
    leagueName: "Fall Marathon League",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/men/12.jpg",
      username: "mike_power",
    },
    imageUri: "https://picsum.photos/600/400?random=3",
    caption: "Day 7 of my streak. Feeling stronger every run!",
    timestamp: "1d ago",
    postType: "challenge",
    comments: [{ id: "3", user: "anna", text: "Consistency king 👑" }],
    liked: false,
    likesCount: 42,
    status: "Completed",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/women/65.jpg",
      username: "linda",
    },
    caption: "Kicking off the Winter Sprint League ❄️🔥",
    timestamp: "2d ago",
    postType: "league",
    liked: true,
    likesCount: 60,
    leagueName: "Winter Sprint League",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/men/76.jpg",
      username: "tony_runner",
    },
    imageUri: "https://picsum.photos/600/400?random=5",
    caption: "Trail run vibes 🌲🏃‍♂️",
    timestamp: "3d ago",
    postType: "challenge",
    comments: [{ id: "4", user: "sammy", text: "Looking strong!" }],
    liked: true,
    likesCount: 12,
    status: "In Progress",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/women/28.jpg",
      username: "emma_fit",
    },
    caption: "Joined the Spring Marathon League 🌸🏃‍♀️",
    timestamp: "4d ago",
    postType: "league",
    liked: false,
    likesCount: 30,
    leagueName: "Spring Marathon League",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/men/52.jpg",
      username: "chris_run",
    },
    imageUri: "https://picsum.photos/600/400?random=6",
    caption: "5k sprint today! 🏃‍♂️💨",
    timestamp: "5d ago",
    postType: "challenge",
    comments: [
      { id: "5", user: "julia", text: "Impressive speed!" },
      { id: "6", user: "mark", text: "Go go go!" },
    ],
    liked: true,
    likesCount: 15,
    status: "In Progress",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/women/33.jpg",
      username: "nina_fitness",
    },
    caption: "Summer Sprint League starts today! ☀️",
    timestamp: "6d ago",
    postType: "league",
    liked: true,
    likesCount: 50,
    leagueName: "Summer Sprint League",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/men/44.jpg",
      username: "alex_runner",
    },
    imageUri: "https://picsum.photos/600/400?random=7",
    caption: "Evening jog along the river 🌊",
    timestamp: "1w ago",
    postType: "challenge",
    comments: [{ id: "7", user: "luke", text: "Nice view!" }],
    liked: false,
    likesCount: 8,
    status: "Completed",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/women/49.jpg",
      username: "olivia_fit",
    },
    caption: "Autumn Marathon League 🍁🏃‍♀️",
    timestamp: "1w ago",
    postType: "league",
    liked: true,
    likesCount: 22,
    leagueName: "Autumn Marathon League",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/men/36.jpg",
      username: "david_run",
    },
    imageUri: "https://picsum.photos/600/400?random=8",
    caption: "Speed training session complete ⚡",
    timestamp: "1w ago",
    postType: "challenge",
    comments: [{ id: "8", user: "maria", text: "Beast mode!" }],
    liked: true,
    likesCount: 19,
    status: "In Progress",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/women/55.jpg",
      username: "kate_fit",
    },
    caption: "Winter League prep ❄️",
    timestamp: "1w ago",
    postType: "league",
    liked: false,
    likesCount: 14,
    leagueName: "Winter League",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/men/23.jpg",
      username: "ryan_runner",
    },
    imageUri: "https://picsum.photos/600/400?random=9",
    caption: "10k challenge done 💪",
    timestamp: "1w ago",
    postType: "challenge",
    comments: [{ id: "9", user: "sophie", text: "Crushed it!" }],
    liked: false,
    likesCount: 33,
    status: "Completed",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/women/61.jpg",
      username: "lisa_fit",
    },
    caption: "Spring League kickoff 🌸",
    timestamp: "2w ago",
    postType: "league",
    liked: true,
    likesCount: 25,
    leagueName: "Spring League",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/men/29.jpg",
      username: "kevin_runner",
    },
    imageUri: "https://picsum.photos/600/400?random=10",
    caption: "Hill repeats today ⛰️",
    timestamp: "2w ago",
    postType: "challenge",
    comments: [{ id: "10", user: "tom", text: "Painful but worth it!" }],
    liked: true,
    likesCount: 20,
    status: "In Progress",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/women/35.jpg",
      username: "anna_fit",
    },
    caption: "Summer League fun ☀️",
    timestamp: "2w ago",
    postType: "league",
    liked: false,
    likesCount: 17,
    leagueName: "Summer League",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/men/18.jpg",
      username: "josh_runner",
    },
    imageUri: "https://picsum.photos/600/400?random=11",
    caption: "5k evening sprint 🏃‍♂️💨",
    timestamp: "2w ago",
    postType: "challenge",
    comments: [{ id: "11", user: "lucas", text: "Nice pace!" }],
    liked: true,
    likesCount: 12,
    status: "In Progress",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/women/41.jpg",
      username: "sophia_fit",
    },
    caption: "Autumn League 🍁",
    timestamp: "3w ago",
    postType: "league",
    liked: true,
    likesCount: 28,
    leagueName: "Autumn League",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/men/50.jpg",
      username: "brad_runner",
    },
    imageUri: "https://picsum.photos/600/400?random=12",
    caption: "Morning tempo run 🌅",
    timestamp: "3w ago",
    postType: "challenge",
    comments: [{ id: "12", user: "nina", text: "Looking good!" }],
    liked: false,
    likesCount: 16,
    status: "Completed",
  },
  {
    user: {
      avatarUri: "https://randomuser.me/api/portraits/women/29.jpg",
      username: "emma_league",
    },
    caption: "Winter League starting soon ❄️",
    timestamp: "3w ago",
    postType: "league",
    liked: true,
    likesCount: 32,
    leagueName: "Winter League",
  },
];
