# Simple Podfile for basic iOS deployment without external dependencies

platform :ios, '16.0'
use_frameworks!

target 'foris' do
  # No external dependencies for basic deployment
  # Dependencies can be added later via Swift Package Manager or CocoaPods
  
  target 'forisTests' do
    inherit! :search_paths
  end
end

# Post-install script to configure build settings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Set minimum deployment target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      
      # Set Swift version
      config.build_settings['SWIFT_VERSION'] = '5.9'
      
      # Optimize for size in release builds
      if config.name == 'Release'
        config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
      end
    end
  end
end